- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Compile C program
      shell: gcc -o compileC/hello_world compileC/hello_world.c

    - name: Run C file
      shell: ./compileC/hello_world