- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

- name: Compile C program
  hosts: all
  tasks:
    - name: Compile C program
      cmd: gcc  -o compileC/hello_world.c hello_world
           ./hello_world
